// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3p4I9Vmpk4BPcYFFcbL-jEd979My5RGs',
    appId: '1:270820082369:web:8c181b998f038e41ef0a40',
    messagingSenderId: '270820082369',
    projectId: 'caronas-utfpr-pg-7ef49',
    authDomain: 'caronas-utfpr-pg-7ef49.firebaseapp.com',
    storageBucket: 'caronas-utfpr-pg-7ef49.appspot.com',
    measurementId: 'G-V5F4K9VT11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzdtsrYK3hloBZrgUxMdqAI4gZhQHD8Pc',
    appId: '1:270820082369:android:e3c90ff68cfa0664ef0a40',
    messagingSenderId: '270820082369',
    projectId: 'caronas-utfpr-pg-7ef49',
    storageBucket: 'caronas-utfpr-pg-7ef49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1IZK3GC1wXei2hEsMdMJzilcLogAbTus',
    appId: '1:270820082369:ios:44e3bd7d02ac619cef0a40',
    messagingSenderId: '270820082369',
    projectId: 'caronas-utfpr-pg-7ef49',
    storageBucket: 'caronas-utfpr-pg-7ef49.appspot.com',
    iosBundleId: 'com.example.caronasUtfpr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1IZK3GC1wXei2hEsMdMJzilcLogAbTus',
    appId: '1:270820082369:ios:4c474f4bb02e0620ef0a40',
    messagingSenderId: '270820082369',
    projectId: 'caronas-utfpr-pg-7ef49',
    storageBucket: 'caronas-utfpr-pg-7ef49.appspot.com',
    iosBundleId: 'com.example.caronasUtfpr.RunnerTests',
  );
}
